---
version: 2.0

phases:
  pre_build:
    commands: 
      - "echo Before Building the application..."
      - "cd /home/ubuntu/AndroidBuildAutomationSample"
      - "chmod +x ./gradlew"
  build:
    commands: 
      - "echo \"Build process start for Android application\""
      - "echo \"Cleaning..\""
      - "./gradlew clean"
      - "echo \"cleanBuildCache..\""
      - "./gradlew cleanBuildCache"
      - "echo \"Build .. \""
      - "./gradlew build"
      - "echo \"assembleDebug..\""
      - "./gradlew assembleDebug"
  post_build:
    commands:
      - "echo \"Build process completed\""	  
artifacts: 
  discard-paths: true
  files: 
    - "echo \"Copy APK to output folder\""
    - ./android/app/build/outputs/**/*.apk
